<a href="https://colab.research.google.com/github/NishanRegmi/Deep-Learning/blob/main/keras_tuner_hyperparameter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('/content/diabetes.csv')

In [3]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
df.shape

(768, 9)

In [5]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [6]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [10]:
X = scaler.fit_transform(X)

In [11]:
X

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=41)

In [53]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense, Dropout

In [21]:
model = Sequential()

In [22]:
model.add(Dense(32, activation='relu', input_dim = 8))
model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [18]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         1,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,377 (5.38 KB)

 Trainable params: 1,377 (5.38 KB)

 Non-trainable params: 0 (0.00 B)

In [23]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [24]:
history = model.fit(X_train, y_train, epochs=100, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 3s 75ms/step - accuracy: 0.6661 - loss: 0.6237 - val_accuracy: 0.6429 - val_loss: 0.6368
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6906 - loss: 0.5776 - val_accuracy: 0.6688 - val_loss: 0.5990
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7231 - loss: 0.5480 - val_accuracy: 0.6948 - val_loss: 0.5716
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7476 - loss: 0.5277 - val_accuracy: 0.6948 - val_loss: 0.5520
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.5138 - val_accuracy: 0.6883 - val_loss: 0.5397
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7655 - loss: 0.5036 - val_accuracy: 0.7078 - val_loss: 0.5280
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7736 - loss: 0.4955 - val_accuracy: 0.7208 - val_loss: 0.5173
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4889 - val_accuracy: 0.7208 - val_loss: 0.5082
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4834 - val_accuracy: 0.7273 - val_loss: 0.5005
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4792 - val_accuracy: 0.7273 - val_loss: 0.4923
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4750 - val_accuracy: 0.7273 - val_loss: 0.4873
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4714 - val_accuracy: 0.7338 - val_loss: 0.4830
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4688 - val_accuracy: 0.7403 - val_loss: 0.4785
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7834 - loss: 0.4659 - val_accuracy: 0.7403 - val_loss: 0.4752
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4635 - val_accuracy: 0.7468 - val_loss: 0.4747
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4619 - val_accuracy: 0.7468 - val_loss: 0.4734
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4598 - val_accuracy: 0.7532 - val_loss: 0.4688
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4581 - val_accuracy: 0.7597 - val_loss: 0.4660
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4562 - val_accuracy: 0.7532 - val_loss: 0.4642
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4543 - val_accuracy: 0.7532 - val_loss: 0.4643
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7866 - loss: 0.4533 - val_accuracy: 0.7532 - val_loss: 0.4642
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4521 - val_accuracy: 0.7532 - val_loss: 0.4638
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4511 - val_accuracy: 0.7727 - val_loss: 0.4598
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4498 - val_accuracy: 0.7727 - val_loss: 0.4587
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4491 - val_accuracy: 0.7792 - val_loss: 0.4571
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4482 - val_accuracy: 0.7792 - val_loss: 0.4576
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4466 - val_accuracy: 0.7662 - val_loss: 0.4562
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7866 - loss: 0.4460 - val_accuracy: 0.7597 - val_loss: 0.4568
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4457 - val_accuracy: 0.7727 - val_loss: 0.4551
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4449 - val_accuracy: 0.7727 - val_loss: 0.4560
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4443 - val_accuracy: 0.7857 - val_loss: 0.4533
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4428 - val_accuracy: 0.7792 - val_loss: 0.4538
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4423 - val_accuracy: 0.7792 - val_loss: 0.4532
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4423 - val_accuracy: 0.7727 - val_loss: 0.4549
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4411 - val_accuracy: 0.7792 - val_loss: 0.4531
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4405 - val_accuracy: 0.7727 - val_loss: 0.4520
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4398 - val_accuracy: 0.7987 - val_loss: 0.4530
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4389 - val_accuracy: 0.7727 - val_loss: 0.4516
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4383 - val_accuracy: 0.7857 - val_loss: 0.4497
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4380 - val_accuracy: 0.7792 - val_loss: 0.4498
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4377 - val_accuracy: 0.7792 - val_loss: 0.4487
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4364 - val_accuracy: 0.7727 - val_loss: 0.4484
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4358 - val_accuracy: 0.7792 - val_loss: 0.4486
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4355 - val_accuracy: 0.7922 - val_loss: 0.4484
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4349 - val_accuracy: 0.7792 - val_loss: 0.4492
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4345 - val_accuracy: 0.7857 - val_loss: 0.4516
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4343 - val_accuracy: 0.7857 - val_loss: 0.4526
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4343 - val_accuracy: 0.7857 - val_loss: 0.4528
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4334 - val_accuracy: 0.7727 - val_loss: 0.4520
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7932 - loss: 0.4328 - val_accuracy: 0.7662 - val_loss: 0.4488
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4322 - val_accuracy: 0.7792 - val_loss: 0.4499
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4312 - val_accuracy: 0.7857 - val_loss: 0.4533
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4315 - val_accuracy: 0.7857 - val_loss: 0.4537
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7964 - loss: 0.4310 - val_accuracy: 0.7857 - val_loss: 0.4513
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4308 - val_accuracy: 0.7857 - val_loss: 0.4496
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4303 - val_accuracy: 0.7727 - val_loss: 0.4473
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4295 - val_accuracy: 0.7727 - val_loss: 0.4485
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4291 - val_accuracy: 0.7727 - val_loss: 0.4484
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4289 - val_accuracy: 0.7727 - val_loss: 0.4470
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7964 - loss: 0.4284 - val_accuracy: 0.7857 - val_loss: 0.4471
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4279 - val_accuracy: 0.7792 - val_loss: 0.4464
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4279 - val_accuracy: 0.7727 - val_loss: 0.4472
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7932 - loss: 0.4274 - val_accuracy: 0.7792 - val_loss: 0.4461
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4271 - val_accuracy: 0.7857 - val_loss: 0.4491
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8029 - loss: 0.4266 - val_accuracy: 0.7857 - val_loss: 0.4484
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8013 - loss: 0.4262 - val_accuracy: 0.7792 - val_loss: 0.4494
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8046 - loss: 0.4255 - val_accuracy: 0.7792 - val_loss: 0.4488
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8013 - loss: 0.4255 - val_accuracy: 0.7857 - val_loss: 0.4463
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7997 - loss: 0.4251 - val_accuracy: 0.7792 - val_loss: 0.4490
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7997 - loss: 0.4246 - val_accuracy: 0.7792 - val_loss: 0.4509
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8013 - loss: 0.4244 - val_accuracy: 0.7792 - val_loss: 0.4497
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7980 - loss: 0.4237 - val_accuracy: 0.7727 - val_loss: 0.4478
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8013 - loss: 0.4239 - val_accuracy: 0.7727 - val_loss: 0.4460
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7997 - loss: 0.4236 - val_accuracy: 0.7792 - val_loss: 0.4471
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4238 - val_accuracy: 0.7792 - val_loss: 0.4467
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4232 - val_accuracy: 0.7857 - val_loss: 0.4473
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4221 - val_accuracy: 0.7792 - val_loss: 0.4471
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4224 - val_accuracy: 0.7792 - val_loss: 0.4476
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4216 - val_accuracy: 0.7727 - val_loss: 0.4486
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8013 - loss: 0.4211 - val_accuracy: 0.7727 - val_loss: 0.4476
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4214 - val_accuracy: 0.7727 - val_loss: 0.4463
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8094 - loss: 0.4208 - val_accuracy: 0.7792 - val_loss: 0.4451
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4209 - val_accuracy: 0.7857 - val_loss: 0.4457
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4197 - val_accuracy: 0.7792 - val_loss: 0.4445
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7980 - loss: 0.4199 - val_accuracy: 0.7792 - val_loss: 0.4452
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7980 - loss: 0.4195 - val_accuracy: 0.7662 - val_loss: 0.4485
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4188 - val_accuracy: 0.7727 - val_loss: 0.4485
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4187 - val_accuracy: 0.7857 - val_loss: 0.4526
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7997 - loss: 0.4190 - val_accuracy: 0.7857 - val_loss: 0.4495
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4181 - val_accuracy: 0.7792 - val_loss: 0.4488
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4184 - val_accuracy: 0.7987 - val_loss: 0.4521
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7997 - loss: 0.4173 - val_accuracy: 0.7857 - val_loss: 0.4500
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8029 - loss: 0.4172 - val_accuracy: 0.7662 - val_loss: 0.4477
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8029 - loss: 0.4171 - val_accuracy: 0.7727 - val_loss: 0.4472
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4169 - val_accuracy: 0.7857 - val_loss: 0.4473
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4162 - val_accuracy: 0.7857 - val_loss: 0.4500
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7964 - loss: 0.4160 - val_accuracy: 0.7792 - val_loss: 0.4476
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4158 - val_accuracy: 0.7857 - val_loss: 0.4475
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.4154 - val_accuracy: 0.7857 - val_loss: 0.4487
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4151 - val_accuracy: 0.7792 - val_loss: 0.4498

In the above process, we manually select everything i.e. hidden layers, activation function and so on. So to find the best parameter, we can use keras tuner as hyperparameter tuner assistant.

**Hyperparameter Tunning - optimizer**

In [27]:
import kerastuner as kt

/tmp/ipykernel_544/1654478174.py:1: DeprecationWarning: `import kerastuner` is deprecated, please use `import keras_tuner`.
  import kerastuner as kt

In [28]:
def build_model(hp):
  model = Sequential()

  model.add(Dense(32, activation='relu', input_dim=8))
  model.add(Dense(1, activation='sigmoid'))

  optimizer = hp.Choice('optimizer', values=['adam', 'rmsprop', 'adadelta', 'sgd'])

  model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])
  return model

In [30]:
tuner = kt.RandomSearch(build_model, objective='val_accuracy', max_trials=5)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [31]:
tuner.search(X_train, y_train, epochs=5, validation_data = (X_test, y_test))

Trial 4 Complete [00h 00m 04s]
val_accuracy: 0.7467532753944397

Best val_accuracy So Far: 0.7467532753944397
Total elapsed time: 00h 00m 15s

In [33]:
#best hyperparameter
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [34]:
#best model
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [35]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [36]:
model.fit(X_train, y_train, batch_size = 32, epochs=100, initial_epoch=5, validation_data=(X_test, y_test))

Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 47ms/step - accuracy: 0.7671 - loss: 0.5007 - val_accuracy: 0.7597 - val_loss: 0.4990
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4880 - val_accuracy: 0.7468 - val_loss: 0.4906
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4813 - val_accuracy: 0.7532 - val_loss: 0.4836
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4765 - val_accuracy: 0.7532 - val_loss: 0.4779
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7769 - loss: 0.4730 - val_accuracy: 0.7403 - val_loss: 0.4733
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4698 - val_accuracy: 0.7532 - val_loss: 0.4694
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4670 - val_accuracy: 0.7532 - val_loss: 0.4666
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4653 - val_accuracy: 0.7597 - val_loss: 0.4629
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4633 - val_accuracy: 0.7662 - val_loss: 0.4596
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.4611 - val_accuracy: 0.7662 - val_loss: 0.4556
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4597 - val_accuracy: 0.7727 - val_loss: 0.4545
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4584 - val_accuracy: 0.7727 - val_loss: 0.4530
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4570 - val_accuracy: 0.7727 - val_loss: 0.4502
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4558 - val_accuracy: 0.7727 - val_loss: 0.4488
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7769 - loss: 0.4545 - val_accuracy: 0.7727 - val_loss: 0.4487
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4537 - val_accuracy: 0.7727 - val_loss: 0.4497
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.4530 - val_accuracy: 0.7727 - val_loss: 0.4482
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7801 - loss: 0.4524 - val_accuracy: 0.7727 - val_loss: 0.4452
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7818 - loss: 0.4516 - val_accuracy: 0.7662 - val_loss: 0.4436
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7801 - loss: 0.4508 - val_accuracy: 0.7662 - val_loss: 0.4420
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7834 - loss: 0.4503 - val_accuracy: 0.7727 - val_loss: 0.4422
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7818 - loss: 0.4496 - val_accuracy: 0.7727 - val_loss: 0.4426
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7850 - loss: 0.4489 - val_accuracy: 0.7727 - val_loss: 0.4417
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7866 - loss: 0.4479 - val_accuracy: 0.7857 - val_loss: 0.4403
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7850 - loss: 0.4473 - val_accuracy: 0.7857 - val_loss: 0.4398
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7834 - loss: 0.4473 - val_accuracy: 0.7857 - val_loss: 0.4394
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7850 - loss: 0.4464 - val_accuracy: 0.7792 - val_loss: 0.4402
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4460 - val_accuracy: 0.7792 - val_loss: 0.4394
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4454 - val_accuracy: 0.7792 - val_loss: 0.4394
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4450 - val_accuracy: 0.7727 - val_loss: 0.4397
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4442 - val_accuracy: 0.7727 - val_loss: 0.4398
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7915 - loss: 0.4439 - val_accuracy: 0.7792 - val_loss: 0.4399
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4435 - val_accuracy: 0.7857 - val_loss: 0.4388
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4428 - val_accuracy: 0.7662 - val_loss: 0.4381
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4422 - val_accuracy: 0.7792 - val_loss: 0.4377
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4418 - val_accuracy: 0.7857 - val_loss: 0.4393
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4409 - val_accuracy: 0.7727 - val_loss: 0.4381
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4404 - val_accuracy: 0.7792 - val_loss: 0.4406
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4401 - val_accuracy: 0.7792 - val_loss: 0.4396
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4395 - val_accuracy: 0.7727 - val_loss: 0.4395
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4388 - val_accuracy: 0.7792 - val_loss: 0.4397
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4384 - val_accuracy: 0.7857 - val_loss: 0.4390
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4381 - val_accuracy: 0.7792 - val_loss: 0.4395
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4380 - val_accuracy: 0.7792 - val_loss: 0.4401
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7866 - loss: 0.4374 - val_accuracy: 0.7792 - val_loss: 0.4401
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4367 - val_accuracy: 0.7857 - val_loss: 0.4386
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4366 - val_accuracy: 0.7792 - val_loss: 0.4387
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4363 - val_accuracy: 0.7857 - val_loss: 0.4394
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4355 - val_accuracy: 0.7857 - val_loss: 0.4386
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4354 - val_accuracy: 0.7857 - val_loss: 0.4382
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4345 - val_accuracy: 0.7662 - val_loss: 0.4382
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4341 - val_accuracy: 0.7792 - val_loss: 0.4386
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4337 - val_accuracy: 0.7857 - val_loss: 0.4394
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4337 - val_accuracy: 0.7792 - val_loss: 0.4376
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4331 - val_accuracy: 0.7792 - val_loss: 0.4377
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4328 - val_accuracy: 0.7792 - val_loss: 0.4373
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4325 - val_accuracy: 0.7727 - val_loss: 0.4373
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7932 - loss: 0.4320 - val_accuracy: 0.7857 - val_loss: 0.4369
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4318 - val_accuracy: 0.7857 - val_loss: 0.4367
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4310 - val_accuracy: 0.7857 - val_loss: 0.4381
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4309 - val_accuracy: 0.7857 - val_loss: 0.4382
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4306 - val_accuracy: 0.7857 - val_loss: 0.4382
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4304 - val_accuracy: 0.7727 - val_loss: 0.4369
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4299 - val_accuracy: 0.7792 - val_loss: 0.4376
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4297 - val_accuracy: 0.7792 - val_loss: 0.4385
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4293 - val_accuracy: 0.7857 - val_loss: 0.4376
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4287 - val_accuracy: 0.7857 - val_loss: 0.4373
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4286 - val_accuracy: 0.7857 - val_loss: 0.4370
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4282 - val_accuracy: 0.7857 - val_loss: 0.4380
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4277 - val_accuracy: 0.7857 - val_loss: 0.4381
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4274 - val_accuracy: 0.7857 - val_loss: 0.4394
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4273 - val_accuracy: 0.7857 - val_loss: 0.4385
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4272 - val_accuracy: 0.7857 - val_loss: 0.4389
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4269 - val_accuracy: 0.7857 - val_loss: 0.4391
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4262 - val_accuracy: 0.7857 - val_loss: 0.4380
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7964 - loss: 0.4262 - val_accuracy: 0.7857 - val_loss: 0.4375
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4254 - val_accuracy: 0.7857 - val_loss: 0.4374
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4255 - val_accuracy: 0.7727 - val_loss: 0.4360
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7866 - loss: 0.4249 - val_accuracy: 0.7727 - val_loss: 0.4353
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4243 - val_accuracy: 0.7792 - val_loss: 0.4350
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4242 - val_accuracy: 0.7792 - val_loss: 0.4353
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4235 - val_accuracy: 0.7857 - val_loss: 0.4355
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4238 - val_accuracy: 0.7857 - val_loss: 0.4361
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4234 - val_accuracy: 0.7857 - val_loss: 0.4353
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7980 - loss: 0.4225 - val_accuracy: 0.7857 - val_loss: 0.4361
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4226 - val_accuracy: 0.7857 - val_loss: 0.4355
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4224 - val_accuracy: 0.7857 - val_loss: 0.4340
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4217 - val_accuracy: 0.7792 - val_loss: 0.4340
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4220 - val_accuracy: 0.7857 - val_loss: 0.4367
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4217 - val_accuracy: 0.7857 - val_loss: 0.4352
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7948 - loss: 0.4213 - val_accuracy: 0.7857 - val_loss: 0.4359
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7915 - loss: 0.4207 - val_accuracy: 0.7857 - val_loss: 0.4341
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7980 - loss: 0.4208 - val_accuracy: 0.7857 - val_loss: 0.4338
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7980 - loss: 0.4203 - val_accuracy: 0.7857 - val_loss: 0.4339
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7948 - loss: 0.4202 - val_accuracy: 0.7857 - val_loss: 0.4369

**Hyperparameter tunning - no. of neurons**

In [40]:
def build_model(hp):
  model = Sequential()
  units = hp.Int('units', min_value=8, max_value=128, step=8) #(start, end, step)

  model.add(Dense(units=units, activation = 'relu', input_dim=8))
  model.add(Dense(1, activation='sigmoid'))

  model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

  return model

In [41]:
tuner = kt.RandomSearch(build_model, objective='val_accuracy', max_trials=5, directory='my_dir')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [42]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 5 Complete [00h 00m 04s]
val_accuracy: 0.7402597665786743

Best val_accuracy So Far: 0.7597402334213257
Total elapsed time: 00h 00m 19s

In [43]:
tuner.get_best_hyperparameters()[0].values

{'units': 120}

In [44]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [45]:
model.fit(X_train, y_train, epochs=100, initial_epoch=5, validation_data=(X_test, y_test))

Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 3s 67ms/step - accuracy: 0.7736 - loss: 0.4821 - val_accuracy: 0.7662 - val_loss: 0.4747
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4720 - val_accuracy: 0.7597 - val_loss: 0.4660
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7752 - loss: 0.4662 - val_accuracy: 0.7597 - val_loss: 0.4581
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4620 - val_accuracy: 0.7532 - val_loss: 0.4544
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7769 - loss: 0.4588 - val_accuracy: 0.7597 - val_loss: 0.4491
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4570 - val_accuracy: 0.7662 - val_loss: 0.4456
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4555 - val_accuracy: 0.7662 - val_loss: 0.4426
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4532 - val_accuracy: 0.7727 - val_loss: 0.4407
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4517 - val_accuracy: 0.7662 - val_loss: 0.4394
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7834 - loss: 0.4491 - val_accuracy: 0.7727 - val_loss: 0.4388
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4489 - val_accuracy: 0.7792 - val_loss: 0.4390
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4468 - val_accuracy: 0.7727 - val_loss: 0.4406
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4463 - val_accuracy: 0.7857 - val_loss: 0.4367
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4449 - val_accuracy: 0.7727 - val_loss: 0.4367
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4443 - val_accuracy: 0.7857 - val_loss: 0.4343
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4420 - val_accuracy: 0.7792 - val_loss: 0.4326
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4413 - val_accuracy: 0.7792 - val_loss: 0.4321
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4406 - val_accuracy: 0.7792 - val_loss: 0.4316
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4393 - val_accuracy: 0.7792 - val_loss: 0.4322
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4388 - val_accuracy: 0.7792 - val_loss: 0.4309
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4378 - val_accuracy: 0.7727 - val_loss: 0.4297
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4372 - val_accuracy: 0.7792 - val_loss: 0.4270
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4363 - val_accuracy: 0.7792 - val_loss: 0.4288
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4351 - val_accuracy: 0.7792 - val_loss: 0.4279
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4342 - val_accuracy: 0.7792 - val_loss: 0.4278
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4337 - val_accuracy: 0.7792 - val_loss: 0.4266
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4332 - val_accuracy: 0.7922 - val_loss: 0.4281
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4323 - val_accuracy: 0.7727 - val_loss: 0.4299
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4312 - val_accuracy: 0.7727 - val_loss: 0.4307
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4305 - val_accuracy: 0.7792 - val_loss: 0.4287
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4301 - val_accuracy: 0.7792 - val_loss: 0.4291
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4293 - val_accuracy: 0.7792 - val_loss: 0.4296
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4287 - val_accuracy: 0.7792 - val_loss: 0.4277
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4273 - val_accuracy: 0.7857 - val_loss: 0.4304
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4268 - val_accuracy: 0.7857 - val_loss: 0.4291
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7980 - loss: 0.4268 - val_accuracy: 0.7792 - val_loss: 0.4295
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4254 - val_accuracy: 0.7857 - val_loss: 0.4289
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4249 - val_accuracy: 0.7792 - val_loss: 0.4276
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4237 - val_accuracy: 0.7857 - val_loss: 0.4269
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4233 - val_accuracy: 0.7857 - val_loss: 0.4253
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4224 - val_accuracy: 0.7792 - val_loss: 0.4284
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4230 - val_accuracy: 0.7922 - val_loss: 0.4258
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7964 - loss: 0.4210 - val_accuracy: 0.7857 - val_loss: 0.4246
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7997 - loss: 0.4211 - val_accuracy: 0.7792 - val_loss: 0.4233
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8046 - loss: 0.4195 - val_accuracy: 0.7727 - val_loss: 0.4208
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.4192 - val_accuracy: 0.7922 - val_loss: 0.4213
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.4193 - val_accuracy: 0.7922 - val_loss: 0.4237
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8046 - loss: 0.4183 - val_accuracy: 0.7922 - val_loss: 0.4241
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4173 - val_accuracy: 0.7987 - val_loss: 0.4294
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4172 - val_accuracy: 0.7857 - val_loss: 0.4268
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4172 - val_accuracy: 0.7857 - val_loss: 0.4256
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4152 - val_accuracy: 0.7857 - val_loss: 0.4236
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4153 - val_accuracy: 0.7857 - val_loss: 0.4228
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4149 - val_accuracy: 0.7857 - val_loss: 0.4269
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8046 - loss: 0.4145 - val_accuracy: 0.7987 - val_loss: 0.4237
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8029 - loss: 0.4127 - val_accuracy: 0.7987 - val_loss: 0.4224
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8029 - loss: 0.4124 - val_accuracy: 0.7792 - val_loss: 0.4211
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8094 - loss: 0.4127 - val_accuracy: 0.7857 - val_loss: 0.4225
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8062 - loss: 0.4120 - val_accuracy: 0.7857 - val_loss: 0.4236
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8029 - loss: 0.4114 - val_accuracy: 0.7792 - val_loss: 0.4228
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8029 - loss: 0.4101 - val_accuracy: 0.7857 - val_loss: 0.4241
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8013 - loss: 0.4102 - val_accuracy: 0.7857 - val_loss: 0.4245
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7980 - loss: 0.4101 - val_accuracy: 0.7922 - val_loss: 0.4254
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8046 - loss: 0.4095 - val_accuracy: 0.7792 - val_loss: 0.4215
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7980 - loss: 0.4088 - val_accuracy: 0.7792 - val_loss: 0.4220
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8062 - loss: 0.4082 - val_accuracy: 0.7727 - val_loss: 0.4184
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4079 - val_accuracy: 0.7727 - val_loss: 0.4174
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.4081 - val_accuracy: 0.7987 - val_loss: 0.4231
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4067 - val_accuracy: 0.7857 - val_loss: 0.4188
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4061 - val_accuracy: 0.7922 - val_loss: 0.4208
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4057 - val_accuracy: 0.7727 - val_loss: 0.4191
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.4054 - val_accuracy: 0.7987 - val_loss: 0.4250
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4043 - val_accuracy: 0.7987 - val_loss: 0.4259
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4045 - val_accuracy: 0.7857 - val_loss: 0.4233
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.4036 - val_accuracy: 0.7792 - val_loss: 0.4212
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8111 - loss: 0.4033 - val_accuracy: 0.7857 - val_loss: 0.4247
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4022 - val_accuracy: 0.7922 - val_loss: 0.4246
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4030 - val_accuracy: 0.7857 - val_loss: 0.4209
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4009 - val_accuracy: 0.7922 - val_loss: 0.4211
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4016 - val_accuracy: 0.7727 - val_loss: 0.4195
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.4012 - val_accuracy: 0.7727 - val_loss: 0.4185
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4006 - val_accuracy: 0.7727 - val_loss: 0.4191
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8127 - loss: 0.3998 - val_accuracy: 0.8052 - val_loss: 0.4222
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8176 - loss: 0.3998 - val_accuracy: 0.7922 - val_loss: 0.4213
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3987 - val_accuracy: 0.7922 - val_loss: 0.4262
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.3991 - val_accuracy: 0.7922 - val_loss: 0.4198
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.3983 - val_accuracy: 0.7857 - val_loss: 0.4169
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.3967 - val_accuracy: 0.7922 - val_loss: 0.4215
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8143 - loss: 0.3971 - val_accuracy: 0.7922 - val_loss: 0.4233
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8062 - loss: 0.3973 - val_accuracy: 0.7857 - val_loss: 0.4204
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8094 - loss: 0.3965 - val_accuracy: 0.7857 - val_loss: 0.4185
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8143 - loss: 0.3958 - val_accuracy: 0.7857 - val_loss: 0.4226
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.3952 - val_accuracy: 0.7987 - val_loss: 0.4261
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8078 - loss: 0.3947 - val_accuracy: 0.7922 - val_loss: 0.4200
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3942 - val_accuracy: 0.7922 - val_loss: 0.4195

**Hyperparameter tunning - no. of layers**

In [46]:
def build_model(hp):
  model = Sequential()

  model.add(Dense(72, activation = 'relu', input_dim=8))

  for i in range(hp.Int('no. of layers', min_value=1, max_value=10)):
    model.add(Dense(72, activation='relu'))

  model.add(Dense(1, activation='sigmoid'))

  model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

  return model

In [47]:
tuner = kt.RandomSearch(build_model, objective='val_accuracy', max_trials=3, directory='my_dir', project_name='num_layers')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [48]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 3 Complete [00h 00m 08s]
val_accuracy: 0.7792207598686218

Best val_accuracy So Far: 0.7792207598686218
Total elapsed time: 00h 00m 21s

In [49]:
tuner.get_best_hyperparameters()[0].values

{'no. of layers': 10}

In [50]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 26 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [51]:
model.fit(X_train, y_train, epochs=100, initial_epoch=5, validation_data=(X_test, y_test))

Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 7s 97ms/step - accuracy: 0.7752 - loss: 0.4751 - val_accuracy: 0.7403 - val_loss: 0.4717
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7850 - loss: 0.4525 - val_accuracy: 0.7662 - val_loss: 0.4642
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7850 - loss: 0.4469 - val_accuracy: 0.7662 - val_loss: 0.4543
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8062 - loss: 0.4228 - val_accuracy: 0.7597 - val_loss: 0.4722
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8257 - loss: 0.3966 - val_accuracy: 0.7468 - val_loss: 0.5099
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8208 - loss: 0.3982 - val_accuracy: 0.7727 - val_loss: 0.4722
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8339 - loss: 0.3785 - val_accuracy: 0.7403 - val_loss: 0.4774
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8306 - loss: 0.3739 - val_accuracy: 0.7338 - val_loss: 0.5145
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8436 - loss: 0.3551 - val_accuracy: 0.7468 - val_loss: 0.5203
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8583 - loss: 0.3505 - val_accuracy: 0.7532 - val_loss: 0.5691
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8632 - loss: 0.3244 - val_accuracy: 0.7338 - val_loss: 0.5652
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8664 - loss: 0.3378 - val_accuracy: 0.7532 - val_loss: 0.5307
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8762 - loss: 0.3127 - val_accuracy: 0.7597 - val_loss: 0.5472
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8697 - loss: 0.2981 - val_accuracy: 0.7727 - val_loss: 0.6746
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8909 - loss: 0.2756 - val_accuracy: 0.6753 - val_loss: 0.6795
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8990 - loss: 0.2587 - val_accuracy: 0.7662 - val_loss: 0.7460
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8925 - loss: 0.2621 - val_accuracy: 0.7727 - val_loss: 0.6277
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9039 - loss: 0.2338 - val_accuracy: 0.7338 - val_loss: 0.7809
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8974 - loss: 0.2363 - val_accuracy: 0.7532 - val_loss: 0.8114
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9121 - loss: 0.2333 - val_accuracy: 0.7857 - val_loss: 0.8064
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9251 - loss: 0.1923 - val_accuracy: 0.7468 - val_loss: 0.9056
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9365 - loss: 0.1769 - val_accuracy: 0.7597 - val_loss: 0.8955
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9365 - loss: 0.1739 - val_accuracy: 0.7273 - val_loss: 0.8503
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9235 - loss: 0.1833 - val_accuracy: 0.7727 - val_loss: 0.9485
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9365 - loss: 0.1501 - val_accuracy: 0.7468 - val_loss: 1.1065
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9153 - loss: 0.2063 - val_accuracy: 0.7532 - val_loss: 1.0987
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9430 - loss: 0.1397 - val_accuracy: 0.7532 - val_loss: 1.1590
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9446 - loss: 0.1388 - val_accuracy: 0.7403 - val_loss: 1.1655
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9479 - loss: 0.1407 - val_accuracy: 0.7532 - val_loss: 1.1292
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9593 - loss: 0.1094 - val_accuracy: 0.7597 - val_loss: 1.1413
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9446 - loss: 0.1458 - val_accuracy: 0.7468 - val_loss: 1.1845
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9560 - loss: 0.0982 - val_accuracy: 0.7338 - val_loss: 1.2210
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9642 - loss: 0.0935 - val_accuracy: 0.7403 - val_loss: 1.2925
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9544 - loss: 0.1154 - val_accuracy: 0.7792 - val_loss: 1.3192
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9593 - loss: 0.1152 - val_accuracy: 0.7403 - val_loss: 0.8186
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9544 - loss: 0.1027 - val_accuracy: 0.7338 - val_loss: 1.4285
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9625 - loss: 0.0761 - val_accuracy: 0.7662 - val_loss: 1.4168
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9772 - loss: 0.0585 - val_accuracy: 0.7662 - val_loss: 1.6760
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9658 - loss: 0.0852 - val_accuracy: 0.7727 - val_loss: 1.5101
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9821 - loss: 0.0361 - val_accuracy: 0.7792 - val_loss: 2.3643
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9707 - loss: 0.0888 - val_accuracy: 0.7208 - val_loss: 1.7446
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9756 - loss: 0.0977 - val_accuracy: 0.7597 - val_loss: 1.3943
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9707 - loss: 0.0756 - val_accuracy: 0.7662 - val_loss: 1.6356
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9577 - loss: 0.1314 - val_accuracy: 0.7403 - val_loss: 1.6980
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9837 - loss: 0.0445 - val_accuracy: 0.7338 - val_loss: 1.5524
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9870 - loss: 0.0458 - val_accuracy: 0.7273 - val_loss: 1.7278
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9642 - loss: 0.1017 - val_accuracy: 0.7208 - val_loss: 1.6132
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9919 - loss: 0.0224 - val_accuracy: 0.7273 - val_loss: 2.2636
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9935 - loss: 0.0133 - val_accuracy: 0.7143 - val_loss: 2.2575
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9642 - loss: 0.1271 - val_accuracy: 0.7403 - val_loss: 1.8070
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9870 - loss: 0.0437 - val_accuracy: 0.7662 - val_loss: 1.7706
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9756 - loss: 0.0806 - val_accuracy: 0.7597 - val_loss: 1.2601
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9902 - loss: 0.0252 - val_accuracy: 0.7532 - val_loss: 1.6562
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9788 - loss: 0.0683 - val_accuracy: 0.7403 - val_loss: 1.5661
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9886 - loss: 0.0306 - val_accuracy: 0.7532 - val_loss: 1.9763
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9870 - loss: 0.0458 - val_accuracy: 0.7662 - val_loss: 1.7337
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9870 - loss: 0.0630 - val_accuracy: 0.7338 - val_loss: 1.5194
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9951 - loss: 0.0151 - val_accuracy: 0.7532 - val_loss: 1.9236
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9739 - loss: 0.0998 - val_accuracy: 0.7662 - val_loss: 1.5849
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9886 - loss: 0.0403 - val_accuracy: 0.7468 - val_loss: 1.7196
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9886 - loss: 0.0450 - val_accuracy: 0.7792 - val_loss: 1.7586
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9821 - loss: 0.0681 - val_accuracy: 0.7662 - val_loss: 2.1042
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9951 - loss: 0.0246 - val_accuracy: 0.7468 - val_loss: 1.9072
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0016 - val_accuracy: 0.7468 - val_loss: 2.3864
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 4.7106e-04 - val_accuracy: 0.7532 - val_loss: 2.8216
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 1.5308e-04 - val_accuracy: 0.7468 - val_loss: 3.0771
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 6.3143e-05 - val_accuracy: 0.7468 - val_loss: 3.3192
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 3.5808e-05 - val_accuracy: 0.7468 - val_loss: 3.5263
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 2.0009e-05 - val_accuracy: 0.7468 - val_loss: 3.6314
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 9.8290e-06 - val_accuracy: 0.7468 - val_loss: 3.7026
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 7.3692e-06 - val_accuracy: 0.7468 - val_loss: 3.7684
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 5.7879e-06 - val_accuracy: 0.7468 - val_loss: 3.8139
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 4.7628e-06 - val_accuracy: 0.7468 - val_loss: 3.8488
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 4.1294e-06 - val_accuracy: 0.7468 - val_loss: 3.8932
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 3.5883e-06 - val_accuracy: 0.7468 - val_loss: 3.9205
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 3.2068e-06 - val_accuracy: 0.7468 - val_loss: 3.9473
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 2.8950e-06 - val_accuracy: 0.7468 - val_loss: 3.9756
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 2.6022e-06 - val_accuracy: 0.7468 - val_loss: 3.9941
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 2.3808e-06 - val_accuracy: 0.7468 - val_loss: 4.0128
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 2.2066e-06 - val_accuracy: 0.7468 - val_loss: 4.0307
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 2.0572e-06 - val_accuracy: 0.7468 - val_loss: 4.0477
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 1.9082e-06 - val_accuracy: 0.7468 - val_loss: 4.0646
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 1.7844e-06 - val_accuracy: 0.7468 - val_loss: 4.0793
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 1.6811e-06 - val_accuracy: 0.7468 - val_loss: 4.0921
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 1.5791e-06 - val_accuracy: 0.7468 - val_loss: 4.1077
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 1.5063e-06 - val_accuracy: 0.7468 - val_loss: 4.1214
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 1.4302e-06 - val_accuracy: 0.7468 - val_loss: 4.1367
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 1.3540e-06 - val_accuracy: 0.7468 - val_loss: 4.1477
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 1.2936e-06 - val_accuracy: 0.7468 - val_loss: 4.1592
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 1.2352e-06 - val_accuracy: 0.7468 - val_loss: 4.1703
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 1.1821e-06 - val_accuracy: 0.7468 - val_loss: 4.1805
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 1.1322e-06 - val_accuracy: 0.7468 - val_loss: 4.1904
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 1.0901e-06 - val_accuracy: 0.7468 - val_loss: 4.1994
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 1.0471e-06 - val_accuracy: 0.7468 - val_loss: 4.2061
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 1.0108e-06 - val_accuracy: 0.7468 - val_loss: 4.2153

**Choosing right hyperparamter among all**

In [54]:
def build_model(hp):
  model = Sequential()

  counter = 0
  for i in range(hp.Int('num_layers', min_value=1, max_value=10)):
    if counter == 0:
      model.add(
          Dense(
              hp.Int('units'+str(i), min_value = 8, max_value = 128, step = 8),
                             activation = hp.Choice('activation'+str(i), values=['relu', 'tanh', 'elu', 'leaky_relu']),
              input_dim=8
              )
          )
      model.add(Dropout(hp.Choice('dropout'+str(i), values=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])))

    else:
      model.add(
          Dense(
              hp.Int('units'+str(i), min_value=8, max_value=128, step=8),
              activation=hp.Choice('activation'+str(i), values = ['relu', 'tanh', 'elu', 'leaky_rely'])
          )
      )
      model.add(Dropout(hp.Choice('dropout'+str(i), values=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])))

    counter += 1

  model.add(Dense(1, activation='sigmoid'))

  model.compile(optimizer=hp.Choice('optimizer', values=['adam', 'rmsprop', 'sgd', 'adadelta', 'nadam']),
                loss='binary_crossentropy', metrics = ['accuracy'])
  return model

In [55]:
tuner = kt.RandomSearch(build_model, objective='val_accuracy',
                        max_trials=3,
                        directory='my_dir',
                        project_name='final')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [56]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 3 Complete [00h 00m 01s]

Best val_accuracy So Far: 0.6428571343421936
Total elapsed time: 00h 00m 23s

In [57]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 5,
 'units0': 32,
 'activation0': 'elu',
 'dropout0': 0.3,
 'optimizer': 'adam',
 'units1': 8,
 'activation1': 'relu',
 'dropout1': 0.1,
 'units2': 8,
 'activation2': 'relu',
 'dropout2': 0.1,
 'units3': 8,
 'activation3': 'relu',
 'dropout3': 0.1,
 'units4': 8,
 'activation4': 'relu',
 'dropout4': 0.1}

In [58]:
model = tuner.get_best_models()[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 26 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [59]:
model.fit(X_train, y_train, epochs=200, initial_epoch=5, validation_data=(X_test, y_test))

Epoch 6/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 8s 160ms/step - accuracy: 0.6547 - loss: 0.6479 - val_accuracy: 0.6429 - val_loss: 0.6437
Epoch 7/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6564 - loss: 0.6298 - val_accuracy: 0.6429 - val_loss: 0.6179
Epoch 8/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6022 - val_accuracy: 0.6429 - val_loss: 0.5941
Epoch 9/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.5838 - val_accuracy: 0.6429 - val_loss: 0.5780
Epoch 10/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6596 - loss: 0.5727 - val_accuracy: 0.6429 - val_loss: 0.5638
Epoch 11/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6645 - loss: 0.5690 - val_accuracy: 0.6558 - val_loss: 0.5543
Epoch 12/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6938 - loss: 0.5685 - val_accuracy: 0.6623 - val_loss: 0.5455
Epoch 13/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6743 - loss: 0.5588 - val_accuracy: 0.7078 - val_loss: 0.5380
Epoch 14/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6987 - loss: 0.5550 - val_accuracy: 0.7013 - val_loss: 0.5316
Epoch 15/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6710 - loss: 0.5499 - val_accuracy: 0.6948 - val_loss: 0.5319
Epoch 16/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6938 - loss: 0.5563 - val_accuracy: 0.7013 - val_loss: 0.5263
Epoch 17/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6889 - loss: 0.5446 - val_accuracy: 0.7013 - val_loss: 0.5207
Epoch 18/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6987 - loss: 0.5507 - val_accuracy: 0.7013 - val_loss: 0.5183
Epoch 19/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7085 - loss: 0.5357 - val_accuracy: 0.7273 - val_loss: 0.5116
Epoch 20/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7101 - loss: 0.5285 - val_accuracy: 0.7208 - val_loss: 0.5058
Epoch 21/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7199 - loss: 0.5290 - val_accuracy: 0.7208 - val_loss: 0.5031
Epoch 22/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7264 - loss: 0.5487 - val_accuracy: 0.7078 - val_loss: 0.5038
Epoch 23/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7085 - loss: 0.5248 - val_accuracy: 0.7078 - val_loss: 0.5003
Epoch 24/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7231 - loss: 0.5268 - val_accuracy: 0.7208 - val_loss: 0.4976
Epoch 25/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7020 - loss: 0.5335 - val_accuracy: 0.7143 - val_loss: 0.4948
Epoch 26/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6954 - loss: 0.5214 - val_accuracy: 0.7143 - val_loss: 0.4907
Epoch 27/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7052 - loss: 0.5308 - val_accuracy: 0.7273 - val_loss: 0.4878
Epoch 28/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7101 - loss: 0.5332 - val_accuracy: 0.7273 - val_loss: 0.4874
Epoch 29/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7134 - loss: 0.5226 - val_accuracy: 0.7273 - val_loss: 0.4850
Epoch 30/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6808 - loss: 0.5312 - val_accuracy: 0.7273 - val_loss: 0.4833
Epoch 31/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7117 - loss: 0.5148 - val_accuracy: 0.7273 - val_loss: 0.4828
Epoch 32/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7199 - loss: 0.5277 - val_accuracy: 0.7338 - val_loss: 0.4833
Epoch 33/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7524 - loss: 0.5127 - val_accuracy: 0.7403 - val_loss: 0.4818
Epoch 34/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7313 - loss: 0.5209 - val_accuracy: 0.7403 - val_loss: 0.4790
Epoch 35/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7231 - loss: 0.5135 - val_accuracy: 0.7403 - val_loss: 0.4789
Epoch 36/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7459 - loss: 0.5022 - val_accuracy: 0.7403 - val_loss: 0.4781
Epoch 37/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7541 - loss: 0.5002 - val_accuracy: 0.7403 - val_loss: 0.4765
Epoch 38/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7443 - loss: 0.4932 - val_accuracy: 0.7403 - val_loss: 0.4752
Epoch 39/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7492 - loss: 0.5156 - val_accuracy: 0.7403 - val_loss: 0.4744
Epoch 40/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7524 - loss: 0.5191 - val_accuracy: 0.7403 - val_loss: 0.4718
Epoch 41/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7345 - loss: 0.5081 - val_accuracy: 0.7468 - val_loss: 0.4727
Epoch 42/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7671 - loss: 0.4876 - val_accuracy: 0.7468 - val_loss: 0.4726
Epoch 43/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.4927 - val_accuracy: 0.7468 - val_loss: 0.4712
Epoch 44/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7427 - loss: 0.5079 - val_accuracy: 0.7532 - val_loss: 0.4717
Epoch 45/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7557 - loss: 0.4930 - val_accuracy: 0.7597 - val_loss: 0.4727
Epoch 46/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7476 - loss: 0.5124 - val_accuracy: 0.7468 - val_loss: 0.4719
Epoch 47/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7427 - loss: 0.5080 - val_accuracy: 0.7468 - val_loss: 0.4734
Epoch 48/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7443 - loss: 0.5052 - val_accuracy: 0.7468 - val_loss: 0.4753
Epoch 49/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7541 - loss: 0.4853 - val_accuracy: 0.7403 - val_loss: 0.4744
Epoch 50/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7492 - loss: 0.5001 - val_accuracy: 0.7468 - val_loss: 0.4760
Epoch 51/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7378 - loss: 0.4959 - val_accuracy: 0.7468 - val_loss: 0.4753
Epoch 52/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7394 - loss: 0.4922 - val_accuracy: 0.7468 - val_loss: 0.4732
Epoch 53/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7443 - loss: 0.5049 - val_accuracy: 0.7532 - val_loss: 0.4717
Epoch 54/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7329 - loss: 0.4939 - val_accuracy: 0.7532 - val_loss: 0.4709
Epoch 55/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7508 - loss: 0.4971 - val_accuracy: 0.7532 - val_loss: 0.4721
Epoch 56/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7573 - loss: 0.4826 - val_accuracy: 0.7532 - val_loss: 0.4709
Epoch 57/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7410 - loss: 0.5049 - val_accuracy: 0.7597 - val_loss: 0.4699
Epoch 58/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7443 - loss: 0.4929 - val_accuracy: 0.7532 - val_loss: 0.4713
Epoch 59/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7248 - loss: 0.5009 - val_accuracy: 0.7597 - val_loss: 0.4719
Epoch 60/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7638 - loss: 0.4900 - val_accuracy: 0.7597 - val_loss: 0.4695
Epoch 61/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7427 - loss: 0.4991 - val_accuracy: 0.7662 - val_loss: 0.4691
Epoch 62/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7573 - loss: 0.4798 - val_accuracy: 0.7662 - val_loss: 0.4690
Epoch 63/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7410 - loss: 0.4875 - val_accuracy: 0.7727 - val_loss: 0.4707
Epoch 64/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7296 - loss: 0.4941 - val_accuracy: 0.7792 - val_loss: 0.4698
Epoch 65/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7573 - loss: 0.4777 - val_accuracy: 0.7662 - val_loss: 0.4701
Epoch 66/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7345 - loss: 0.4841 - val_accuracy: 0.7662 - val_loss: 0.4712
Epoch 67/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.4750 - val_accuracy: 0.7597 - val_loss: 0.4721
Epoch 68/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7573 - loss: 0.5028 - val_accuracy: 0.7662 - val_loss: 0.4708
Epoch 69/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7508 - loss: 0.4768 - val_accuracy: 0.7597 - val_loss: 0.4672
Epoch 70/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.4872 - val_accuracy: 0.7597 - val_loss: 0.4651
Epoch 71/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7671 - loss: 0.4857 - val_accuracy: 0.7662 - val_loss: 0.4631
Epoch 72/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7313 - loss: 0.4890 - val_accuracy: 0.7597 - val_loss: 0.4630
Epoch 73/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7622 - loss: 0.4723 - val_accuracy: 0.7597 - val_loss: 0.4616
Epoch 74/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7378 - loss: 0.4875 - val_accuracy: 0.7597 - val_loss: 0.4605
Epoch 75/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7345 - loss: 0.4891 - val_accuracy: 0.7662 - val_loss: 0.4623
Epoch 76/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7476 - loss: 0.4791 - val_accuracy: 0.7597 - val_loss: 0.4637
Epoch 77/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.4789 - val_accuracy: 0.7597 - val_loss: 0.4652
Epoch 78/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7459 - loss: 0.4754 - val_accuracy: 0.7597 - val_loss: 0.4652
Epoch 79/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7508 - loss: 0.4779 - val_accuracy: 0.7532 - val_loss: 0.4671
Epoch 80/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.4840 - val_accuracy: 0.7597 - val_loss: 0.4655
Epoch 81/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.4761 - val_accuracy: 0.7662 - val_loss: 0.4626
Epoch 82/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7443 - loss: 0.4892 - val_accuracy: 0.7597 - val_loss: 0.4641
Epoch 83/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7410 - loss: 0.4769 - val_accuracy: 0.7597 - val_loss: 0.4655
Epoch 84/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7459 - loss: 0.4844 - val_accuracy: 0.7597 - val_loss: 0.4675
Epoch 85/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7394 - loss: 0.4882 - val_accuracy: 0.7662 - val_loss: 0.4644
Epoch 86/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7508 - loss: 0.4841 - val_accuracy: 0.7662 - val_loss: 0.4672
Epoch 87/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7573 - loss: 0.4647 - val_accuracy: 0.7597 - val_loss: 0.4678
Epoch 88/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7541 - loss: 0.4787 - val_accuracy: 0.7662 - val_loss: 0.4677
Epoch 89/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7410 - loss: 0.4745 - val_accuracy: 0.7532 - val_loss: 0.4697
Epoch 90/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7524 - loss: 0.4774 - val_accuracy: 0.7532 - val_loss: 0.4688
Epoch 91/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7345 - loss: 0.4787 - val_accuracy: 0.7532 - val_loss: 0.4702
Epoch 92/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7410 - loss: 0.4805 - val_accuracy: 0.7597 - val_loss: 0.4715
Epoch 93/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7655 - loss: 0.4840 - val_accuracy: 0.7597 - val_loss: 0.4727
Epoch 94/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7573 - loss: 0.4705 - val_accuracy: 0.7468 - val_loss: 0.4712
Epoch 95/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7362 - loss: 0.4861 - val_accuracy: 0.7597 - val_loss: 0.4683
Epoch 96/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7394 - loss: 0.4614 - val_accuracy: 0.7597 - val_loss: 0.4687
Epoch 97/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7541 - loss: 0.4644 - val_accuracy: 0.7532 - val_loss: 0.4714
Epoch 98/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7329 - loss: 0.4790 - val_accuracy: 0.7597 - val_loss: 0.4726
Epoch 99/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.4820 - val_accuracy: 0.7792 - val_loss: 0.4725
Epoch 100/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.4622 - val_accuracy: 0.7792 - val_loss: 0.4717
Epoch 101/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7557 - loss: 0.4801 - val_accuracy: 0.7662 - val_loss: 0.4714
Epoch 102/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7410 - loss: 0.4809 - val_accuracy: 0.7727 - val_loss: 0.4726
Epoch 103/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7459 - loss: 0.4940 - val_accuracy: 0.7662 - val_loss: 0.4684
Epoch 104/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.4926 - val_accuracy: 0.7662 - val_loss: 0.4669
Epoch 105/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7508 - loss: 0.4754 - val_accuracy: 0.7597 - val_loss: 0.4673
Epoch 106/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7492 - loss: 0.4722 - val_accuracy: 0.7532 - val_loss: 0.4688
Epoch 107/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4861 - val_accuracy: 0.7727 - val_loss: 0.4628
Epoch 108/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7590 - loss: 0.4746 - val_accuracy: 0.7532 - val_loss: 0.4637
Epoch 109/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7410 - loss: 0.4794 - val_accuracy: 0.7532 - val_loss: 0.4624
Epoch 110/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4785 - val_accuracy: 0.7532 - val_loss: 0.4616
Epoch 111/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7704 - loss: 0.4627 - val_accuracy: 0.7727 - val_loss: 0.4607
Epoch 112/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.4707 - val_accuracy: 0.7597 - val_loss: 0.4637
Epoch 113/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7573 - loss: 0.4759 - val_accuracy: 0.7597 - val_loss: 0.4676
Epoch 114/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7655 - loss: 0.4623 - val_accuracy: 0.7662 - val_loss: 0.4673
Epoch 115/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7638 - loss: 0.4750 - val_accuracy: 0.7662 - val_loss: 0.4666
Epoch 116/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7557 - loss: 0.4746 - val_accuracy: 0.7597 - val_loss: 0.4678
Epoch 117/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7508 - loss: 0.4795 - val_accuracy: 0.7597 - val_loss: 0.4689
Epoch 118/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7573 - loss: 0.4770 - val_accuracy: 0.7597 - val_loss: 0.4669
Epoch 119/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7590 - loss: 0.4701 - val_accuracy: 0.7597 - val_loss: 0.4675
Epoch 120/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7769 - loss: 0.4587 - val_accuracy: 0.7662 - val_loss: 0.4666
Epoch 121/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7590 - loss: 0.4794 - val_accuracy: 0.7662 - val_loss: 0.4681
Epoch 122/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7671 - loss: 0.4621 - val_accuracy: 0.7727 - val_loss: 0.4678
Epoch 123/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7752 - loss: 0.4655 - val_accuracy: 0.7792 - val_loss: 0.4651
Epoch 124/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7704 - loss: 0.4822 - val_accuracy: 0.7792 - val_loss: 0.4645
Epoch 125/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7508 - loss: 0.4774 - val_accuracy: 0.7792 - val_loss: 0.4640
Epoch 126/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7443 - loss: 0.4846 - val_accuracy: 0.7727 - val_loss: 0.4640
Epoch 127/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7752 - loss: 0.4622 - val_accuracy: 0.7727 - val_loss: 0.4649
Epoch 128/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7704 - loss: 0.4621 - val_accuracy: 0.7727 - val_loss: 0.4649
Epoch 129/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7622 - loss: 0.4650 - val_accuracy: 0.7662 - val_loss: 0.4693
Epoch 130/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7671 - loss: 0.4731 - val_accuracy: 0.7727 - val_loss: 0.4701
Epoch 131/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7508 - loss: 0.4633 - val_accuracy: 0.7727 - val_loss: 0.4694
Epoch 132/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7476 - loss: 0.4910 - val_accuracy: 0.7727 - val_loss: 0.4667
Epoch 133/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7524 - loss: 0.4799 - val_accuracy: 0.7727 - val_loss: 0.4696
Epoch 134/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7655 - loss: 0.4706 - val_accuracy: 0.7662 - val_loss: 0.4699
Epoch 135/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7850 - loss: 0.4495 - val_accuracy: 0.7597 - val_loss: 0.4745
Epoch 136/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7459 - loss: 0.4757 - val_accuracy: 0.7597 - val_loss: 0.4759
Epoch 137/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7541 - loss: 0.4527 - val_accuracy: 0.7468 - val_loss: 0.4783
Epoch 138/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7541 - loss: 0.4687 - val_accuracy: 0.7597 - val_loss: 0.4738
Epoch 139/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.4760 - val_accuracy: 0.7468 - val_loss: 0.4720
Epoch 140/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7573 - loss: 0.4752 - val_accuracy: 0.7532 - val_loss: 0.4727
Epoch 141/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7508 - loss: 0.4968 - val_accuracy: 0.7532 - val_loss: 0.4701
Epoch 142/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7508 - loss: 0.4775 - val_accuracy: 0.7597 - val_loss: 0.4680
Epoch 143/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4590 - val_accuracy: 0.7597 - val_loss: 0.4687
Epoch 144/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7524 - loss: 0.4808 - val_accuracy: 0.7532 - val_loss: 0.4711
Epoch 145/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4580 - val_accuracy: 0.7597 - val_loss: 0.4706
Epoch 146/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7655 - loss: 0.4606 - val_accuracy: 0.7597 - val_loss: 0.4676
Epoch 147/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7687 - loss: 0.4655 - val_accuracy: 0.7597 - val_loss: 0.4667
Epoch 148/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7720 - loss: 0.4525 - val_accuracy: 0.7597 - val_loss: 0.4690
Epoch 149/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.4516 - val_accuracy: 0.7597 - val_loss: 0.4699
Epoch 150/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7557 - loss: 0.4617 - val_accuracy: 0.7597 - val_loss: 0.4700
Epoch 151/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7687 - loss: 0.4630 - val_accuracy: 0.7532 - val_loss: 0.4702
Epoch 152/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4735 - val_accuracy: 0.7662 - val_loss: 0.4732
Epoch 153/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7720 - loss: 0.4676 - val_accuracy: 0.7597 - val_loss: 0.4740
Epoch 154/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.4605 - val_accuracy: 0.7662 - val_loss: 0.4723
Epoch 155/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4655 - val_accuracy: 0.7662 - val_loss: 0.4687
Epoch 156/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4685 - val_accuracy: 0.7597 - val_loss: 0.4734
Epoch 157/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4656 - val_accuracy: 0.7597 - val_loss: 0.4757
Epoch 158/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7622 - loss: 0.4583 - val_accuracy: 0.7662 - val_loss: 0.4767
Epoch 159/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4577 - val_accuracy: 0.7597 - val_loss: 0.4806
Epoch 160/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.4787 - val_accuracy: 0.7662 - val_loss: 0.4784
Epoch 161/200